In [1]:
import pandas as pd
import seaborn as sns

In [4]:
dataset = pd.read_csv("mental_health_dataset.csv", low_memory=False)
dataset.head(3)

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [12]:
dataset['Occupation'].value_counts()

Occupation
Housewife    55818
Corporate    47699
Student      44574
Others       41771
Business     39694
Name: count, dtype: int64

In [16]:
dataset['self_employed'].value_counts()

self_employed
No     203046
Yes     22328
Name: count, dtype: int64

In [17]:
dataset['family_history'].value_counts()

family_history
No     135986
Yes     93570
Name: count, dtype: int64

In [18]:
dataset['treatment'].value_counts()

treatment
Yes    118490
No     111066
Name: count, dtype: int64

In [19]:
dataset['Days_Indoors'].value_counts()

Days_Indoors
1-14 days             48095
Go out Every day      46066
31-60 days            45945
More than 2 months    44846
15-30 days            44604
Name: count, dtype: int64

In [20]:
dataset['Growing_Stress'].value_counts()

Growing_Stress
Maybe    79690
Yes      78743
No       71123
Name: count, dtype: int64

In [7]:
dataset['Country'].value_counts()

Country
United States             135776
United Kingdom             39760
Canada                     14846
Australia                   4902
Netherlands                 4463
Ireland                     4322
Germany                     3454
Sweden                      2307
India                       2160
France                      1728
Brazil                      1727
New Zealand                 1586
South Africa                1585
Italy                       1152
Switzerland                 1152
Israel                      1151
Belgium                      722
Poland                       721
Russia                       576
Singapore                    576
Denmark                      576
Greece                       575
Portugal                     288
Costa Rica                   288
Nigeria                      288
Bosnia and Herzegovina       288
Finland                      288
Thailand                     288
Croatia                      288
Mexico                       288
Moldova                      287
Colombia                     287
Georgia                      287
Czech Republic               287
Philippines                  287
Name: count, dtype: int64

In [21]:
dataset['Changes_Habits'].value_counts()

Changes_Habits
Yes      86153
Maybe    72333
No       71070
Name: count, dtype: int64

In [22]:
dataset['Mental_Health_History'].value_counts()

Mental_Health_History
No       79418
Maybe    78158
Yes      71980
Name: count, dtype: int64

In [23]:
dataset['Mood_Swings'].value_counts()

Mood_Swings
Low       80154
Medium    79461
High      69941
Name: count, dtype: int64

In [24]:
dataset['Coping_Struggles'].value_counts()

Coping_Struggles
No     119195
Yes    110361
Name: count, dtype: int64

In [25]:
dataset['Work_Interest'].value_counts()

Work_Interest
No       81858
Maybe    81427
Yes      66271
Name: count, dtype: int64

In [26]:
dataset['Social_Weakness'].value_counts()

Social_Weakness
No       77069
Maybe    76333
Yes      76154
Name: count, dtype: int64

In [27]:
dataset['mental_health_interview'].value_counts()

mental_health_interview
No       183756
Maybe     39321
Yes        6479
Name: count, dtype: int64

In [28]:
dataset['care_options'].value_counts()

care_options
No          91621
Yes         76102
Not sure    61833
Name: count, dtype: int64

In [29]:
dataset = dataset.drop('Timestamp' , axis=1)

In [30]:
dataset.head(3)

,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [31]:
dataset['self_employed'].isnull().sum()

np.int64(65145)

In [32]:
dataset.drop('self_employed',axis = 1 , inplace = True)

In [33]:
dataset.head(3)

,Gender,Country,Occupation,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,Female,United States,Corporate,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,Female,United States,Corporate,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,Female,United States,Corporate,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [35]:
X = dataset.drop('Growing_Stress', axis=1)  # inputs
y = dataset['Growing_Stress']               # output

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in X.columns:
     X[col] = le.fit_transform(X[col].astype(str))

In [37]:
y = le.fit_transform(y.astype(str))

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
from sklearn.naive_bayes import CategoricalNB

model = CategoricalNB()
model.fit(X_train, y_train)

CategoricalNB()

In [41]:
y_pred = model.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.5504096103538483

Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.48      0.46     15844
           1       0.43      0.32      0.37     14288
           2       0.42      0.47      0.45     15705
           3       1.00      1.00      1.00     12267

    accuracy                           0.55     58104
   macro avg       0.57      0.57      0.57     58104
weighted avg       0.55      0.55      0.55     58104


Confusion Matrix:
 [[ 7680  3127  5037     0]
 [ 4606  4638  5044     0]
 [ 5321  2988  7396     0]
 [    0     0     0 12267]]