In [2]:
import pandas as pd
import seaborn as sns

dataset = pd.read_csv("mental_health_dataset.csv", low_memory=False)
dataset.head(3)

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [3]:
dataset = dataset.drop('Timestamp', axis = 1)

In [4]:
dataset.drop('self_employed',axis = 1 , inplace = True)

In [5]:
dataset.head(3)

,Gender,Country,Occupation,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,Female,United States,Corporate,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,Female,United States,Corporate,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,Female,United States,Corporate,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [6]:
X = dataset.drop('Growing_Stress', axis=1)  # inputs
y = dataset['Growing_Stress']

In [ ]:
y = y.map({'Yes': 1, 'No': 0})

In [7]:
X_encoded = pd.get_dummies(X, drop_first=True)

In [9]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X_encoded , y , test_size = 0.2 , random_state = 42)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 1000)
model.fit(X_train , y_train)

ValueError: Input contains NaN

In [11]:
print(X_encoded.isnull().sum().sum())
print(y.isnull().sum())

0
60963

In [12]:
X = X.fillna("Unknown")

In [19]:
X = dataset.drop('Growing_Stress', axis=1)
y = dataset['Growing_Stress']

# Drop rows where target is NaN
mask = y.notna()
X = X[mask]
y = y[mask]

In [35]:
y = y.map({
    'Yes': 1,
    'No': 0,
    'Maybe': 2
})

In [36]:
print(y.isnull().sum())

229556

In [37]:
X = X.fillna("Unknown")

In [38]:
X_encoded = pd.get_dummies(X, drop_first=True)

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    multi_class='multinomial',
    solver='lbfgs'
)

model.fit(X_train, y_train)

ValueError: Input y contains NaN.

In [40]:
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

AttributeError: 'LogisticRegression' object has no attribute 'coef_'